# Based on https://docs.docker.com/compose/rails/
version: "3.4"
services:
  web:
    build:
      target: dev
      context: .
    container_name: omni2_dev
    volumes:
      - .:/myapp
    ports:
      - "3010:3000"
    depends_on:
      - db
